### ISSUE TITLE
Request: $clipboard action

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#131]
This action would copy some data to the clipboard... simple as that!

**Comment by gliechtenstein** [comment]
Sorry just realized this was another undocumented feature (because it's only on iOS so far) Here's the code https://github.com/Jasonette/JASONETTE-iOS/blob/develop/app/Jasonette/JasonUtilAction.m#L197

The syntax is similar to [$util.share](http://docs.jasonette.com/actions/#utilshare)

Here's an example https://jasonbase.com/things/Jym

Going to need to write an Android version and also document. Just opened an issue at the [Android side](https://github.com/Jasonette/JASONETTE-Android/issues/73)

**Comment by gliechtenstein** [comment]
Closing since it already works. The Android side is yet to be implemented. Will update and document when this is ready on the Android side as well
