### ISSUE TITLE
Clear cache of images

### ISSUE THREAD

**Issue by sharipovmarat** [Jasonette/JASONETTE-iOS#145]
How images are caching? How can i clear cache?

issue: 
- Set to cache of images TTL
- or add $cache.clear,  
- or add to $cache.reset something like "delete older than 1 day".... 

problem is that my app taking 200 mb and it's growing..... o_O

**Comment by gliechtenstein** [comment]
Should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/a0cbde00bebc53f18ca1b0fdaf9a8c6222610d5e

Please try pulling from develop and let me know if it works so we can close it!

p.s. It's not a documented feature yet, will need to document it. In the meantime, here's the syntax https://github.com/Jasonette/JASONETTE-iOS/issues/122#issuecomment-274332539

**Comment by sharipovmarat** [comment]
```
"$pull": {
          "type": "$flush",
          "success": {
            "type": "$reload"
          }
        }
```

Thanks @gliechtenstein ! It works!!!
