### ISSUE TITLE
Any code which passes arbitrary parameters to dynamic methods  respondsToSelector:, performSelector

### ISSUE THREAD

**Issue by gordemota** [Jasonette/JASONETTE-iOS#149]
https://forums.developer.apple.com/thread/73640

Any code which passes arbitrary parameters to dynamic methods  respondsToSelector:, performSelector might be rejected.

**Comment by gliechtenstein** [comment]
Yup I was just reading that on Hacker News as well, thanks for the question :)

# rollout.io
There are a couple of things to say about this situation. First, if you read the comment thread on that link, this rejection is about a service called [rollout.io](https://rollout.io). These guys use a clever approach to "hot-patch" the binary itself by downloading Javascript which patches the native code at runtime (which is called "method swizzling"). You can learn more about how they do this here: https://rollout.io/blog/under-the-hood-2016-update/

Other frameworks like React Native handle hot patch in similar ways but these rollout guys have gone a bit further (and may have crossed the line) and so I can see how it can become dangerous potentially. I guess that's what makes them powerful, but at the same time they're walking a thin line, which is probably why the rejections are happening.

# performSelector and respondsToSelector

Here's the important part from the rejection letter

> This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script.

The only things from this paragraph that are relevant to Jasonette are `performSelector` and `respondsToSelector`. However the way that the reviewer phrased it is a bit misleading. I highly doubt they will retire the `performSelector` or `respondsToSelector` methods altogether as these are methods built into many frameworks and even apple's own code and are some of the most important features of objective-c. 

I think what the reviewer was trying to say was these `performSelector` and `respondsToSelector` (and the rest) shouldn't be abused to enable dangerous method swizzling and other similar things.

# How Jasonette is different

You may ask why does Jasonette currently use `performSelector` and `repondsToSelector` then? 

Jasonette uses them for the most innocent purpose possible--just to call methods by name. (For example, if we want to call the `share` method of `JasonUtilAction`, we call a `performSelector` on `JasonUtilAction` and pass `share` as argument). This is very normal use case and there are tons of libraries and frameworks and even Apple's own code which makes use of this. 

This is a different from method swizzling.

Jasonette doesn't do any "method swizzling", "hot patching", "downloading a script code at runtime", or any of that sort. All of these involve changing the binary's behavior itself.

However in case of Jasonette **all the native methods are already compiled and built into the binary when you ship it** and **it is impossible to change the behavior of each method or class.**

Think of it this way. All apps run by executing functions from classes. 

What these hot patch services do is actually change the implementations of the functions at runtime, whereas Jasonette NEVER touches the functions themselves. 

Instead, Jasonette does its job by simply passing different arguments (JSON objects) to the **same function** and **same class**.


# Conclusion
So what does this mean?

1. We'll see how this turns out but my guess is Apple is rejecting them for a good reason, and my guess is this whole thing is about the rollout.io company.
2.  Jasonette is the safest framework when it comes to this type of problem, since the binary is never touched once you build it.

**Comment by gordemota** [comment]
Wow, very long and detail writeup. This great to let other know that Jasonette app will not be rejected.
