### ISSUE TITLE
Button layout inconsistency with Android

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#161]
The goal is to make the button in iOS look like what we see in Android. 

<img width="936" alt="screen shot 2017-04-08 at 11 58 33 pm" src="https://cloud.githubusercontent.com/assets/3887694/24829551/4e4334d2-1cb7-11e7-8361-a7ca50b83b5c.png">

Testable code: https://jasonbase.com/things/RLd7.json

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/bbaba2b02dd1842332653d3734a112bff603c1af

Please check&confirm that it works!

ios | android
--|--
![img_1442](https://cloud.githubusercontent.com/assets/16613330/24830875/3e0b77e2-1c5c-11e7-9502-53ea11be415f.PNG) | ![screenshot_20170408-130451](https://cloud.githubusercontent.com/assets/16613330/24830874/3dfb7cb6-1c5c-11e7-9594-6ee0e8fb2e34.png)

Please check and confirm

**Comment by drwasho** [comment]
Kicking ass and taking names!
