### ISSUE TITLE
Button image inconsistency between iOS and Android

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#162]
Testable code: https://jasonbase.com/things/LEYV.json

## iOS

![simulator screen shot 9 apr 2017 12 05 44 am](https://cloud.githubusercontent.com/assets/3887694/24829605/4e18c728-1cb8-11e7-928a-1ed42bde8cfb.png)

## Android

![screenshot_1491660364](https://cloud.githubusercontent.com/assets/3887694/24829606/56b2f84a-1cb8-11e7-877c-4b0dfca6995e.png)

**Comment by gliechtenstein** [comment]
OK after thinking about this for a while, I came to a conclusion that we should make the `width` and `height` describe the clickable region instead of the image size.

If we don't do that, we will always have to make the image size equal to the clickable region.  At first I thought this was the natural way to go, but upon thinking about it more I realized there are some cases where this will make it overly complicated. For example if you want to just create a button that looks like:

```
[        (image)          ]
```

you will need to create a total of three buttons and disguise them as a single button (because you want the blank region to be clickable as well)

So the final policy is:

1. The `width` and `height` of a button is the width and height of the **clickable region**.
2. Then, the actual dimension of the image inside (in case of an image button) is auto-determined. The image gets resized to fit into that button region.
3. Text buttons have a default of 5 pixels padding
4. Image buttons have a default of 0 pixels padding


So, the latest commit https://github.com/Jasonette/JASONETTE-iOS/commit/bbaba2b02dd1842332653d3734a112bff603c1af should make it work that way. 

I just tried and here are my screenshots:

android | ios
---| ---
![screenshot_20170408-130252](https://cloud.githubusercontent.com/assets/16613330/24830959/0682bc34-1c5e-11e7-8a9b-322f278ec8fc.png) | ![img_1441](https://cloud.githubusercontent.com/assets/16613330/24830960/0684808c-1c5e-11e7-88fa-decd1142b7e8.PNG)

Please check and confirm!

**Comment by drwasho** [comment]
Beautiful
