### ISSUE TITLE
button text in develop branch currently being cut off

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#165]
this button component:

```
                        {
                          "style": {
                            "align": "left",
                            "color": "#ffffff",
                            "corner_radius": "2",
                            "background": "#3f51b5",
                            "font": "HelveticaNeue",
                            "height": "45",
                            "padding": "20",
                            "size": "22"
                          },
                          "type": "button",
                          "text": "  Listen [English]  "
                        }
                      ]
                    },
```

produces the following:

![fullsizerender 1](https://cloud.githubusercontent.com/assets/5496117/25068710/54c55c76-2221-11e7-9ff3-40d52a65620e.jpg)

**Comment by gliechtenstein** [comment]
That's because the height is fixed at 45, and since the padding is 20, which means you're left with 45-20-20 = 5, so the label gets cut off. 

This was an intended change to make the text button be more consistent with image buttons. It used to be unclear what "height" meant for image buttons in the previous versions. It could be the image size, or it could be the size of the clickable region. With the recent update, it's been fixed to "clickable region" http://docs.jasonette.com/components/#button and as a result it was much simpler to go this way (padding is inside the height region) instead of the CSS model (where padding is outside of the "height" area by default but can also be inside the height region if you use `border-sizing: border-box`)

Sorry about the confusion. I will try to document these things more in the future.

Anyway, to make sure this doesn't break, try either setting a lower padding or setting a smaller font size. You could also increase the height. Hope this makes sense.

**Comment by ghost** [comment]
makes sense, thanks.
