### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by rborn** [Jasonette/JASONETTE-iOS#17]
Hi,
This is an amazing thing you're doing here, I wonder if you considered an android port? 
Would be the next cross-platform framework that would rule them all 😁

**Comment by gliechtenstein** [comment]
Yup that's the plan! https://github.com/Jasonette/JASONETTE-iOS/issues/9

Let's keep this issue open just because I feel like this will turn into a FAQ :)

**Comment by thedumbtechguy** [comment]
Hi, I already commented on HN, but thought I would follow up here.

I am very interested in working on the Android port of this, but as this is "JASONETTE-iOS" do you mind creating a "JASONETTE-Android" which we can fork and start working on?

It would be great to keep it all under the same banner.

**Comment by gliechtenstein** [comment]
OK, kinda getting overwhelmed with all the issues so gonna close this for now, since I think my answer (YES) resolves it. 

Before I close, let me clarify the roadmap: The plan is to release a rough draft version of Android as soon as I can. In order to move faster, I will try to only cover the skeleton (layout rendering, state machine, template engine, and minimal actions and components) and open it up as soon as those are ready, and hoping that we can quickly improve upon it and add things like additional components and actions then.

**Comment by gliechtenstein** [comment]
Guys, as promised, I'm ready to show something, and sharing here first. Ping me on Slack if you have Android!
