### ISSUE TITLE
Feature request: local mix-ins for $network.request & $require

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#177]
There is some static data that some of my views constantly need to fetch, and it would save resources and significantly speed things up if it could fetch them via a local mix-in. 

Kudos for @steve21124 for kicking this off a while back.

**Comment by drwasho** [comment]
After working around this problem the last couple of days, I've come to the conclusion that this is unnecessary. 

All you need to do is add the data as a sibling object to `$jason` and then do a self-mixin to access the data. In my personal experience I'd also recommend setting it as a local variable before using/manipulating the data to avoid potential errors.

**Comment by gliechtenstein** [comment]
Just for the record, local $require is supported. 

As for a local `$network.request`, it doesn't really make sense as it's not really making any network requests, so that's that.

Related thread https://github.com/Jasonette/JASONETTE-iOS/issues/213

As of today, local view JSON, local mixin JSON, local $require JSON all supported cross-platform both on Android and iOS
