### ISSUE TITLE
app hang's iPhone (iOS) 

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#183]
Using Jason app this url works the first time, then hangs the phone

http://kadist-ios.herokuapp.com/knews_with_templates?channel=kadist&lang=en

steps:

- open above link in jason
- after a few seconds template is evaluated and replaces body, all good
- then click the top/left back link (in header)
- open above link 
- hangs on jason.body never replaced by template evaluation, even though I see the networking completed.

Sometimes I can't even open my phone for a while after this happens.

Thank You!!

**Comment by gliechtenstein** [comment]
Could you post a quick video? 

I just followed your instruction but couldn't replicate it, maybe I misunderstand the instruction. Thanks!

**Comment by ghost** [comment]
I can make a video. I just tried it again just now and it reproduces for me. The second time coming into the app the initial animated gif never gets replaced by the real content and I can't even kill Jason for a while. It always recovers and I can restart Jason. All I do is open the json URL and then back out once the content proper loads and open it again. I have the latest Jason app.

**Comment by ghost** [comment]
@gliechtenstein - 

gif/video
![issue183](https://cloud.githubusercontent.com/assets/5496117/25753711/75fc96ca-3171-11e7-9c6c-5d0fd4e04395.gif)
 demo attached.

**Comment by ghost** [comment]
on Android this works fine, just tried that. If you can help with a few possible breakpoints I can try to debug it.

**Comment by gliechtenstein** [comment]
Just fixed this with https://github.com/Jasonette/JASONETTE-iOS/commit/17a10af24349aaf3d8257fce998e34c0747f6cff

This was caused by a bug in SDWebImage library where the `completion` handler was not being called reliably (as reported here https://github.com/rs/SDWebImage/issues/1209)

The solution was to directly use the `SDWebImageDownloader.sharedDownloader`. 

Please try it out and let me know if it works!
