### ISSUE TITLE
It's so cool , but the page load was very slower, urgent need to improve！

### ISSUE THREAD

**Issue by cheft** [Jasonette/JASONETTE-iOS#19]
It's so cool , but the page load was very slower, urgent need to improve！

**Comment by gliechtenstein** [comment]
By page load, do you mean the app launch? Or the jasonette.com web page?

Just in case it's the former I've just recorded app launches on my phone. Watch the videos below to compare how Jasonette **actually loads faster** than other traditional Internet connected apps because the amount of hard-coded code is minimal.

[![traditional apps](https://i.ytimg.com/vi_webp/r1HNuWPXxMQ/sddefault.webp)](https://www.youtube.com/watch?v=r1HNuWPXxMQ)

[![jasonette apps](https://i.ytimg.com/vi_webp/ap4eaSdTjzs/hqdefault.webp)](https://www.youtube.com/watch?v=ap4eaSdTjzs)

Hope this answers the question! Or if I misunderstood, please let me know :)

**Comment by cheft** [comment]
May be a network problem, I was in China region.
Watch the [Video](https://youtu.be/dTOueu96dog)
View the [Code](https://github.com/cheft/jasonette-cnbeta-app)
![simulator screen shot 2016 11 8 10 55 07](https://cloud.githubusercontent.com/assets/1567209/20085547/c3b99538-a5a4-11e6-8542-1c778b5127e1.png)

**Comment by gliechtenstein** [comment]
Can you try:
1. Serving the JSON from a non-github server? : Serving JSON from Github is not recommended by Github themselves and is known to be slow. I use it in my examples just for the sake of making it open source, but to make sure it performs well, I recommend not using Github. Another bad thing about hosting on Github is their server caches your JSON so whenever you make a change to your JSON it takes quite a while to reflect your change.
2. Serving the JSON from a server in China: This would be the best since it should load faster.

Let me know if this improves things!

**Comment by mathiasrw** [comment]
(tiny input: IF you want to host json files on github, then use http://rawgit.com/ to serve them)

**Comment by gliechtenstein** [comment]
Closing this for now, because I really think this is a network traffic issue. Please reopen if anyone finds this otherwise. You can check the attached videos above for reference.
