### ISSUE TITLE
Bug: Interrupting $network.requests with actions

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#197]
**Description**

If you have initiated a network request, there are two problems that the user will encounter:

1. They cannot initiate trigger an action within the current view while the network request is being performed
2. If the user touches a tab footer, the next view will fail to load.

**Code for testing**

1. https://jasonbase.com/things/A8lK.json (tab 1)
2. https://jasonbase.com/things/ePXR.json (tab 2)

**Comment by drwasho** [comment]
Some additional instructions:

This view allows you to initiate a network request by touching a button. The loading spinner will activate during this process.

You can test two things while the spinner is going:

1. Touch the 'navigation' button, which will attempt to open a web view
2. Touch the footer tab 2. To properly replicate the bug, do not load the tab 2 view prior to initiating the network request.

**Comment by gliechtenstein** [comment]
This should be fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/e7503305fb93c0bc3142f0c14ca14afd128c227d and https://github.com/Jasonette/JASONETTE-iOS/commit/555fed3409e8692944e01b0192cde92de32e1a2e

There were two problems:

1. when "loading": "true" is set, the loading indicator was blocking user interactions, which is why you couldn't press the button to navigate away. I think this was the intended behavior of the loading indicator itself, but thought about it a bit more and realized that since Jasonette is basically like a browser, users expect a similar behavior, which means, users expect to interact with ui elements asynchronously even when some network request is happening. So I allowed user interaction when the loading indicator is running https://github.com/Jasonette/JASONETTE-iOS/commit/e7503305fb93c0bc3142f0c14ca14afd128c227d

2. As I mentioned above, user interaction was being blocked when loading indicator was running, but for some reason this didn't block everything, and allowed the tabbar tap event to slip through, which is why you could tap the tab bar while you couldn't tap the button. Anyway, this part doesn't matter anymore since user interaction is completely allowed now. 

3. The most critical problem of all was that the tab 2 won't load even when you *do* navigate into it. This was because whenever a view comes into view it needs to reload content from a URL, but it first looks at a flag called `executing`. If it finds that an action is currently running, it doesn't reload the view. Here's the background: This feature is important for things like oauth actions or any type of action that involves a flow that looks like this : 

```
Step1. Jasonette calls a 3rd party app via URL scheme
Step 2. 3rd party app (Possibly browser) does something and returns back to Jasonette via URL Scheme
Step 3. Jasonette receives the info and keeps running
```

Oauth works this way because it opens safari to authenticate and comes back. But since the entire action should be treated as atomic, Jasonette sets the `executing` flag and doesn't reload the view between step2 and step3. Otherwise the entire auth process would be reset.

Anyway, transitioning to another tab bar is not equivalent to this situation so the `executing` flag should be explicitly set to NO, so the new view can reload. Here's the fix https://github.com/Jasonette/JASONETTE-iOS/commit/555fed3409e8692944e01b0192cde92de32e1a2e



Please check and confirm that it works!

**Comment by drwasho** [comment]
Confirmed!
