### ISSUE TITLE
Request: pass responses as arguments if an error is encountered

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#199]
This particularly relevant to network requests where error responses are informative and can trigger follow-up actions.

**Comment by gliechtenstein** [comment]
Fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/efe89808eda8a88f83d1bd5eb61a58f86469b813

Here's what happens when you load the following JSON:

```
{
  "$jason": {
    "head": {
      "actions": {
        "$load": {
          "type": "$network.request",
          "options": {
            "url": "http://localhost"
          },
          "success": {
            "type": "$render"
          },
          "error": {
            "type": "$util.alert",
            "options": {
              "title": "error",
              "description": "{{JSON.stringify($jason, null, 2)}}"
            }
          }
        }
      }
    }
  }
}
```

<img width="487" alt="screen shot 2017-06-15 at 3 17 39 pm" src="https://user-images.githubusercontent.com/16613330/27197845-d2a0ebce-51dd-11e7-8385-da92f8bc323c.png">
