### ISSUE TITLE
selecting "SanFranciscoDisplay-Heavy" (or other SF fonts) doesn't work

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#204]
When trying font's on iOS 10, iPhone 7+ I am able to pick some fonts found at iosfonts.com but none of the SanFrancisco fonts work (appears to default back to a standard font)

```
                "my_text_class": {
                    "size": "28",
                    "font": "SanFranciscoDisplay-Heavy",
                    "color": "#000000"
                },
```

**Comment by gliechtenstein** [comment]
I just looked this up and found these facts:

1. The San Francisco font **is** the system font of iOS.
2. Which means the default font is San Francisco (if you leave out "font" field it will be just a regular San Francisco font)
3. And since it's the system font, you can't just use them using a font name like that.
4. However according to the link below, internally it's accessed as as `SFUIDisplay-Heavy` so you maybe able to get around this by using this name, but this font name is not set in stone and may change depending on what Apple decides to do with it.

Check out the stack overflow answer : https://stackoverflow.com/questions/33460612/set-sf-ui-display-bold-as-label-font

I'm outside now so can't try at the moment but could you try the `SFUDisplay-Heavy` option and see if that works for now?

**Comment by ghost** [comment]
thanks for responding - I knew the default/standard font was SF but there are many variants of SF and I wanted to use the heavy font. **When I use `.SFUIDisplay-Heavy` (note leading dot) it does indeed work**. 

One good possibility that would be resilient to Apple changing these "private font names" in Jasonette is to support an alternative way of influencing font choice, for example

```
"style": {
  "font-weight": ...
}
```

where ... could be one of 

```
UltraLight
Thin
Light
(default) Regular
Medium
Semibold
Bold
Heavy
Black
```
I never _really_ want to pick any font other than SF, but I would like to be able to use variants of it (as above)

I know what you're going to say :) "submit a pull request!

**Comment by gliechtenstein** [comment]
Haha you can just create an issue about this too.

I do think the font system needs an upgrade at some point not just because of this issue but also because of the compatibility issue with Android. Just need some time to sit down and think about it (but don't have one at the moment, so would like to keep track of this so we can get back to it when ready)
