### ISSUE TITLE
resilience to errors

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#220]
I had a problem where the app's json was being generated on the server and there was an exception, the server sent back nothing that Jasonette could process so the users got a white screen from which they couldn't recover without killing the app (which they didn't know how to do).

Would it be possible to add some resilience so that if they at least try it again later it will retry. Some mechanism to recover from errors like this would make the app more robust. Better still show a default view with an error message and an option to pull to refresh/try again.

(ps, what does the "global" branch add? Is there a release notes for this feature please?

**Comment by gliechtenstein** [comment]
actions have an `error` callback and in this particular case I think you can handle errors using the `error` callback of the `$network.request` action. If there's an error, you can decide to render a different template for example.

**Comment by ghost** [comment]
but this is on the main app's url, so it opens, fetches the content, gets garbage back because the server threw an exception, there's no json for Jasonette to trigger an error.

**Comment by ghost** [comment]
Other than stopping my server from throwing exceptions which I can do, what do you think to the idea of making a redirector? I could build my app with the "home" url of an endpoint that sends down a jasonette json view with a network.request that has a success action that causes a "replace" with the real home view and an error action that shows an error?

Is that going to work though with the footer tabs because I'm guessing that the redirected home view will cause problems?

**Comment by gliechtenstein** [comment]
Ah i now see what you mean, yes there currently isn't a way to handle this. 

I think there can be many ways to deal with this problem, but it would be best if we can come up with the lowest level solution which can handle all other similar cases.

One idea just from top of my head is having an `offline.json` which automatically gets triggered if the initial load fails. Then depending on what you want to do there, you have multiple options:

1. Just update the `file://offline.json` to use that as the offline screen
2. Update `file://ofline.json` so that it doesn't do any rendering but automatically redirect to any URL you desire via `$href` with a `transition: "replace"`

But I think there can be many other ways, so would like to give it some more thought.


That said, I didn't really understand your paragraph, would be great if you could break it down...

> I could build my app with the "home" url of an endpoint that sends down a jasonette json view with a network.request that has a success action that causes a "replace" with the real home view and an error action that shows an erro

**Comment by ghost** [comment]
what I meant was basically what you suggested but rather than be in the offline location it be sourced from the server  but does the same thing, replaces the view with the real one on success. I didn't realize that I could have an offline.json, that should work I think, I'll code it and try it out tonight.

**Comment by gliechtenstein** [comment]
Ah no, the `offline.json` was just an idea. Just to clarify, there isn't a way to handle this situation, it could be the `offline.json` approach, it could be specifying an alternative offline address. Will need to think about it a bit more.

Just thinking about the two ideas I think the two can be combined:

1. Have an additional field on the `seetings.plist` which defines the URL that needs to load in case the primary url fails
2. That secondary URL can be either a remote URL or a local URL (such as `file://offline.json`)

**Comment by ghost** [comment]
that would work perfectly, possibly it would be better if offline.json was *always* loaded first, this would then trigger fetching the primary url, but would allow both error handling and a better loading experience because something offline could be shown before the primary url renders.

**Comment by gliechtenstein** [comment]
resolved with https://github.com/Jasonette/JASONETTE-iOS/pull/227
