### ISSUE TITLE
Bug: Local use of $back fails to trigger $show

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#228]
This is quite an edge case, but it's reproducible:

View 1: https://jasonbase.com/things/qVnE (save as `back_test_1.json`)
View 2: https://jasonbase.com/things/GVkJ (save as `back_test_2.json`)

Drag and drop these files into `file://`

When you load `back_test_1.json` you will see this:

![simulator screen shot 30 jun 2017 5 27 04 pm](https://user-images.githubusercontent.com/3887694/27725371-5a39781c-5db9-11e7-9fc1-61b2341c6db9.png)

The top component is a label that will conditionally indicate whether or not a global variable called `$global.back_message_test` exists or not. When you first load the view, it won't exist and will tell you as much.

Touch the black button to go to the second view (`back_test_2.json`):

![simulator screen shot 30 jun 2017 5 27 40 pm](https://user-images.githubusercontent.com/3887694/27725391-70b35662-5db9-11e7-8570-0ee769647a40.png)

If you touch the black button in this view, it will save a message in `$global.back_message_test` and initiate a `$back` upon success, taking you back to `back_test_1.json`.

Because `back_test_1.json` renders with a `$show` action, it should be checking to see if the variable exists, but it doesn't. For some reason, the `$show` action doesn't appear to trigger. Pulling the view to `$reload` will show you the correct label message indicating that the variable exists.

To run negative test you can touch the grey 'clear global variable' button, go the next view, and tab back and then $pull to $reload.

**The edge case** is that this bug only happens for local files, not for hosted files.

**Comment by gliechtenstein** [comment]
Normally when you transition to another view, we clear the memory so that a new action call chain can start fresh from the new view. 

This is implemented in href but not on $back, so when the view transitioned it still thinks it's in the middle of the old action call chain, which is where the bug came from. With this fix, we make sure the stack and register are cleared as well as other cleanup tasks are taken care of, before transitioning back.

Let me know if this fixes it

**Comment by drwasho** [comment]
Fixed!
