### ISSUE TITLE
web view should have an option to not show the url box

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#23]
i think for safety reasons, there should be an option (possibly default enabled, if you ask me!) to not show or enable the url box, much less let the user interact with it.

a simple "Done" should suffice in the header, i think.

**Comment by gliechtenstein** [comment]
Could you elaborate what you mean by security reasons?

Also as far as I am aware, the web view we use doesn't let users interact with the url bar. Have you experienced otherwise?

**Comment by cpg** [comment]
Basically, if there is an open URL bar, the app can be directed by the user to go anywhere, which can affect ratings, e.g. whether it can be allowed in certain contexts, like education/kids, etc.

Also, if one wants to render certain content, it may be best that the actual url to the content (e.g. session IDs, or user IDs, etc.), not be known to users, for it could open easy paths to obtaining or hacking that content. Granted doing this just makes it much harder to obtain, so in a way it's just obfuscation, which is not truly security, it just elevates the level of attack vectors.

Sorry, I was not sure if there was any way to interact with it. Even viewing or copying the URL is not good.

Then again, if it does not let user interact with the url bar, why show it at all? What's the upside? It's just ugly and takes space. In a previous project I found that it's possible to remove the URL from the standard native web view.

**Comment by gliechtenstein** [comment]
Actually as far as security is concerned, it works both ways. Jasonette uses SFSafariViewController for displaying `"type": "web"` views. 

SFSafariViewController is the most secure way to display web content and that's why Apple recommends using this whenever you need to access web within an app.

Before this we used to be able to use what's called UIWebView to display web content. This had all the features you mentioned--it can be embedded in a view without displaying url, no address bar, etc--but this is actually dangerous because if you don't know which domain you're looking at, it can be used for phishing. This is why Apple is pushing SFSafariViewController.

As far as I know you can't edit the address bar on SFSafariViewController. It only displays the domain because of the reasons I mentioned above. But when you touch it it doesn't let you edit.

If you are concerned about parameters showing up on urls when someone presses the share button or safari button at the bottom I think you should not include those sensitive data. These can be sniffed if people really wanted to anyway. Hope this makes sense!

**Comment by gliechtenstein** [comment]
I am closing this because this is something that Apple would not allow anyway on the Appstore, and I'm positive this introduces security holes. Please reopen if anyone has a different view. Thanks!

**Comment by cpg** [comment]
This assertion is nothing short of baseless, near as I can tell. There are probably tens of thousands of apps that render  embedded HTML content using *WebView APIs. There is a whole class of such apps called "hybrid apps." Things like Phonegap, Cordova, Sencha, and a [zillion of other apps](https://duckduckgo.com/?q=WKWebView+site%3Aitunes.apple.com&t=ffsb&ia=web) (and these are just the ones mentioning WKWebView), including apps to [compare UIWebView to WKWebView](https://itunes.apple.com/us/app/webview-wkwebview-uiwebview/id928647773?mt=8), editors, incognito browsers, offline browsers, online games, site recorders, a billion news aggregators and apps that have news in them, etc. etc.

The web page for [WKWebView](https://developer.apple.com/reference/webkit/wkwebview) in no way mentions or conveys that using this view is not proper.

Among all [popular search results on WKWebView](https://duckduckgo.com/?q=WKWebView&t=ffsb&ia=web) there is not a single one indicating this would be in any way forbidden or not allowed in the app store.

Do you have any information supporting your assertion that "Apple would not allow it anyway"? (not that Apple should be exempted from a stiff challenge)
