### ISSUE TITLE
Can't Submit App Due to Provisioning?

### ISSUE THREAD

**Issue by tomershvueli** [Jasonette/JASONETTE-iOS#25]
I built an app with Jasonette in one day (yay!). But am now having trouble submitting it to the App Store due to provisioning issues? See attached image. What's weird is that my Jasonette XCode project is /not/ in my Applications folder, like this popup says. I've also followed most of the stack overflows to due with this error and am still getting nowhere. Just wondering if this is something you've come across. 

<img width="1015" alt="screen shot 2016-11-08 at 7 58 03 am" src="https://cloud.githubusercontent.com/assets/1024355/20100000/45aca952-a589-11e6-8865-af0974142778.png">

**Comment by gliechtenstein** [comment]
Sorry for the inconvenience, we'll need to document this process better (currently there are none about the actual submit, actually there's an issue open for this https://github.com/Jasonette/JASONETTE-iOS/issues/11). Perhaps you can share your experience once you get through this :) 

Anyway, couple of questions for context:
1. Did you create the app bundle id and **distribution** provisioning profile from developer.apple.com? https://developer.apple.com/library/content/qa/qa1830/_index.html
2. Did you create an app with the bundle id from itunesconnect.apple.com before "upload to app store"?

One last thing: Please make sure to **uncheck** "use bitcode" option when you submit. For some reason that option doesn't work well at the moment. We don't really need it anyway since Jasonette is super small already and bitcode is supposed to optimize code size.

Please keep us posted!

**Comment by james1238** [comment]
bitcode also allows apple to recompile your app to run on new processors. It can make apps bigger in size

**Comment by gliechtenstein** [comment]
@james1238 that's a great point, I didn't know about that. Yeah we don't need no bitcode! It's already small :)

**Comment by gliechtenstein** [comment]
Just confirming that I just tried downloading, building and submitting an app from scratch from beginning to end just to make sure.

I followed my own direction above: create an app on developer.apple.com, create a distribution provisioning profile and run it, then build. Create an app on itunesconnect.apple.com with the same bundle id. And come back to XCode and submit. It just went through. 

Screenshot:

![img_1117](https://cloud.githubusercontent.com/assets/16613330/20109518/6af2cd84-a5ae-11e6-943d-f4b3d7c6ace8.PNG)

**Comment by gliechtenstein** [comment]
@thetomester13 did you ever get it to work? Please let us know. Thanks!

**Comment by tomershvueli** [comment]
Hey, sorry for the absence. I was eventually able to get it up and running! I think it just ended up being a provisioning profile issue... 😒 one of these days I'll get it right on the first try! Only other thing to note is I got an email warning me about the 'Missing Push Notification Entitlement' since my app isn't using pushes. Either way, it should drop soon hopefully! Is there a 'powered by Jasonette' page somewhere?

**Comment by gliechtenstein** [comment]
@thetomester13 Yeah the push notification thing is kind of pain in the ass at the moment. If you are still having trouble with this, please feel free to just use the master branch instead of develop branch. In the meantime we'll try to figure out a way to fix this. (Another way to do this is to just turn on the push capabilities from XCode).

As for the "powered by Jasonette" page, I am thinking about it! Will probably start by adding a new channel to slack, but maybe eventually add a wiki page on github where people can post their own apps.
