### ISSUE TITLE
Bug: Janky scrolling

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#255]
This has been reported a couple of times informally, but I've finally got around to making a replicable test (sent to @gliechtenstein privately).

The effects can be seen here: http://imgur.com/H2SX9eL

Apologies for the terrible gif quality

**Comment by gliechtenstein** [comment]
Thanks for writing the reproducible code. I was glad to finally have the consistently failing code that I literally spent the whole day trying to fix this, turns out it only requires a couple of lines to fix this.

Anyway, unlike what I speculated at first, the problem was NOT about horizontal sections (although horizontal sections still do need to be optimized).

The real problem was that the estimated height of headers wasn't correctly being set. When a section doesn't have a header, the estimated height should be set to 0 but that was not how it was working. This was a clear bug, and i can see that this fix gets rid of the jumping issue. Here's the commit: https://github.com/Jasonette/JASONETTE-iOS/commit/6b731be6810e9360cf047fa988f515d03a8edc7d

Hopefully this fixes a lot of other cases. Please try out and confirm

**Comment by drwasho** [comment]
This is an excellent fix, definitely cleared away almost all of the jankyness (about 95%) in the test.

I'm still not clear on the section headers and what you mean by that?

I'll also try and generate some reproducible code for the parts that are still giving us trouble.

**Comment by gliechtenstein** [comment]
Awesome. 

> I'm still not clear on the section headers and what you mean by that?

One of the reasons why native is more performant than webview when it comes to building apps is because on mobile the memory is limited so we need to recycle the cells as much as possible. This is how you can build an app with 10000 items and it would perform the same as an app with 10 items when scrolling. For example when you have 10000 items, the app only loads like 10 items (only the visible ones) at first, and as you start scrolling, it takes the item that becomes invisible, and recycles it to fill it in with a newly visible item's content. This gives the illusion that there actually is 10000 items but like I said, this is achieved only with 10 items on the memory. This works pretty much the same way on Android on iOS. Anyway If you try to use a webview for this, initially it may work ok when it's a simple app, but as the view becomes more complex it will slow down because a webview doesn't have this mechanism.

But in order to facilitate this, the programmer needs to do a lot of work as you can imagine, such as determining which item to recycle into which item, and providing info on what each cell's height will be, or in case of more advanced layout like Jasonette where each item can have any dimension, it needs to be able to provide an estimated height so that the view can calculate the viewport's height correctly.

If this height is not correctly computed, you may end up with a view that actually has 10000 pixels height but the app thinks it only has 1000 pixels height. What happens next is, as you start scrolling the app constantly recalculates the heights as a new item comes into viewport. Even though the estimated height was incorrect, since we have access to the actual height whenever an item comes into view, we can correct this initially-incorrectly-estimated-height as use scrolls along.

And this is where the jumping happens. Since it constantly recalculates the height and tries to correct the incorrect height as you scroll, it keeps jumping to where it thinks is the correct position in the viewport.

So the key to minimize jumping is if you can provide correct estimates to begin with. The current code does its best to do so, but there was a bug. In this particular case, if a section doesn't have a header we need to provide `0` as estimate obviously, but the code wasn't taking that condition into account. Normally this works alright even though it's an obvious bug, but this becomes serious when you have many sections, because the algorithm makes the same mistake for every section and the aggregate mistake becomes huge. This is why it's so visible in this case.

Hope this makes sense. Please keep the bug+reproducible code coming, i would like to exterminate all these jumping issues as much as possible.
