### ISSUE TITLE
Not Needed

### ISSUE THREAD

**Issue by clsource** [Jasonette/JASONETTE-iOS#262]
- **Don't submit issue reports here, they will be closed automatically. Instead submit Jasonette issue reports to the [Jasonette issues repository](https://github.com/Jasonette/Jasonette-issues/issues)**.
- Please do not submit feature requests to the issues repository, instead use the [Jasonette feature requests repository](https://github.com/Jasonette/Jasonette-requests/issues).
- Please do not use the issues repository for Jasonette support, instead use the support forum at [https://forum.jasonette.com/](https://forum.jasonette.com/).
- Always include the Operating System (iOS 10). Also include the smartphone hardware specs when potentially applicable.
- Indicate any 3rd party frameworks or Apis that are being used when potentially applicable.
- When possible please confirm the issue on the [Jason App](https://docs.jasonette.com/jason/) before submitting an issue report.
- When the issue is resolved, please close it.
- For roadmap and project discussion, please use the [Jasonette repository](https://github.com/Jasonette/Jasonette/issues).

**Comment by maks** [comment]
@clsource why the change for this? Why not just label issues submitted here as feature requests as such, to me seems rather confusing to have a separate repo just for feature requests.

**Comment by clsource** [comment]
@maks  As the project will attract more people because it's a super technology. issues and features will start to be unmanageable. It's better to define a cleaner way of separating concerns. This was following the rules of another great opensource project [Processwire](https://github.com/processwire/)

**Comment by clsource** [comment]
Also by having a separate repo we can have a specific issue template for bugs and another issue template for feature requests. Improving both. 👍

**Comment by maks** [comment]
@clsource I've found it easy enough in the past to just manage requests as issues in the same repo, via labels and often users aren't even sure if they are submitting a feature request or bug report.
To be honest that is the first open-src project I've heard of to take that approach.

**Comment by clsource** [comment]
Here is the main benefit.

Please click both links below. 😄 

[Create a new Feature request](https://github.com/Jasonette/Jasonette-requests/issues/new)
[Create a new Bug Report](https://github.com/Jasonette/Jasonette-bugs/issues/new)

**Comment by ghost** [comment]
@clsource  - You can still have different templates for features and bugs without making new repos for them. If the reason was to consolidate bugs/features between iOS and Android versions of Jasonette I would understand the reason for this change but I don't see any benefit in doing it this way. 

The difference between bug and feature request is very subtle, the feature request is that the bug be fixed and the bug is that Jasonette doesn't have X feature. Seriously though it is a very fine line between bug and feature and often one of interpretation. The fact that Jasonette doesn't have UICollectionView for example is probably a feature request, but for someone not familiar with that component just sees that they can't get the layouts to handle what UICollectionView does and sees it as a layout bug. It's all in the interpretation. Labels are better because what a submitter thinks is a bug the resolver can re-assign as a feature, which is much easier than moving an issue between repositories.

Aside from the Processwire repo which I'd never heard of and seems to be an inactive project, I don't know of any other repo that does this. Probably there are many but I am not familiar with them. Take tensorflow for example, ~1000 issues, same repo, labels type:feature for when it's reclassified. Jasonette-ios only has 100 issues, that doesn't seem to be to be anywhere even close to unmanageable. 

I guess it doesn't matter much, just so long as the project is active and continues to improve and fix issues that come up.

**Comment by clsource** [comment]
@darenr After reading your comment and talking with @gliechtenstein and @maks This approach will be ditched. 👍 😄
