### ISSUE TITLE
Modal weirdness

### ISSUE THREAD

**Issue by drwasho** [Jasonette/JASONETTE-iOS#271]
![modal](https://user-images.githubusercontent.com/3887694/30682136-a56c765e-9eeb-11e7-8f57-a83f39db574f.png)

I haven't pulled down the view, it is just erroneously showing the pull-down text.

**Comment by gliechtenstein** [comment]
This has been fixed with https://github.com/Jasonette/JASONETTE-iOS/commit/5838b85e63abe9a74e59ff2691cab854adbbab42

Also with this fix I have removed the "pull to close modal" feature which have been kind of annoying for many users either because it was too sensitive or the other way around.

Please confirm!

**Comment by gliechtenstein** [comment]
I will assume that this has been fixed. Closing.
