### ISSUE TITLE
video in web component no longer working

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#302]
This used to work, not sure at what point it broke.

https://jasonbase.com/things/gXGB

Thanks

**Comment by gliechtenstein** [comment]
I haven't touched the HTML components so this wasn't related to Jasonette but rather related to Vimeo itself. Upon taking a look, this looks like it's related to some weird stuff Vimeo guys are experimenting with https://vimeo.com/forums/help/topic:291053

Quick rant but I honestly don't know why they have such a convoluted way to display videos and keep making these weird buggy decisions.

Anyway the solution was to set the `transparent=0` params as the above post suggested, and setting the height in absolute instead of percentage. Here's a working version. https://jasonbase.com/things/LV53

**Comment by ghost** [comment]
that was fast!! Thank you. much appreciated.
