### ISSUE TITLE
tab shows wrong view (content)

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#334]
I don't have a test case (yet), I'm hoping that there's something that might be evident from the code. I at first didn't believe the person that reported this but it just happened to me. Five tabs, I was clicking around and noticed that the tab I just clicked on was showing the view a different tab! I thought I was going crazy. I clicked between the tabs and consistently the app thought that tab 2 (2nd from left) was tab 4. It wasn't until on tab 2 I did a pull-to-refresh that it showed the right content.

By wrong content I mean it shows the exactly right content but for a completely different tab. The tab bar is showing the correct icon "enabled"

**Comment by gliechtenstein** [comment]
Code-wise I don't think there's any obvious bugs for general usage because I've tested tons of examples while fixing the last bug, I'm guessing most likely an edge case, but edge case is important, so happy to take a look if you can provide any sort of instruction to replicate, and/or a video of this happening.

**Comment by ghost** [comment]
I agree, I spent an hour or so clicking around and couldn't make it reproduce again. Definitely an add edge case, since I seriously doubt I'll ever be able to get a reproducible test case I will go ahead and close this because I can't see any other way to progress.
