### ISSUE TITLE
html component does not work with audio tad

### ISSUE THREAD

**Issue by ghost** [Jasonette/JASONETTE-iOS#55]
```
{
  "type": "html",
  "text": "<audio src=\"https://s3.amazonaws.com/www.textcast.co/icons/yo.mp3\">ERROR</audio>"
}
```
Yields ERROR, it appears that it's not using html5 rendering.

**Comment by gliechtenstein** [comment]
@darenr Yes, currently Jasonette's `html` component implementation is just for simple html display purposes therefore doesn't support complicated html5 elements. That would require an embedding of an entire UIWebView, which we probably will never do since it will have serious performance problems.

Internally, `"type": "html"` components currently use `NSAttributedString` to build basic html components, such as `<p>`, `<li>`, `<img>`, etc. But you can't use more complex elements like `<video>` or `<audio>`, since we are not using the full Webkit engine for this.

But I think it's a good idea to explore this. Maybe we could try using something like [https://github.com/Cocoanetics/DTCoreText](https://github.com/Cocoanetics/DTCoreText) in the future.

**Comment by ghost** [comment]
makes sense, just wasn't sure what was and wasn't allowed in this component.
