### ISSUE TITLE
scrolling not too smooth

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#61]
I see scroll behavior in items that is not as “smooth” as native. There is a little bit of jerkiness when scrolling. You can see it in the View > Sections area of Jasonpedia with the Jason app.

Please disregard the first time that it loads, as it clearly has to load images, maps, etc. After it has loaded, it still has a distinct "jerkiness" to it that you typically not see in native apps (mail, duck duck go ios app, etc.), even when scrolling somewhat slowly.

[My app](https://itunes.apple.com/us/app/racketlogger/id1175588031) has a header, footer and one section with a bunch of items, typically a dozen or so, 6 showing at a time. Every app will improve if the framework is smooth at scrolling.

**Comment by gliechtenstein** [comment]
The example on Jasonpedia (more specifically the "section" view where it showcases multiple components) is choppy because it has tons of distinct components all being rendered simultaneously. This is an edge case, because most apps won't have so many different types of components in one screen. Basically this shouldn't be a problem for 90% of the cases, which includes your case.

What I do want to make sure is if this is actually a problem you are facing with your app right now. If your app actually scrolls noticeably choppy, that should not happen. For most apps with just a couple of distinct component types (image/label) it should scroll smoothly.

If it's actually slow, could you share your code so it can be tested?

**Comment by cpg** [comment]
I'm confused. When I mentioned this in slack, you immediately said you had noticed it as well.

In any case, [here is an example](https://jasonbase.com/things/nwV/) with a long list that shows the effect. It's not *slow* .. but rather it shows also even when scrolling slowly. Because of that, I would think it might not be a performance issue (i.e. it does not happen only when scrolling fast, or with lots of interactive things like maps, input boxes, etc., ... just a list of items seems to do it).

This was mostly filed to track the issue, though it's not a high priority one, just a nitpick where the framework feels just a little bit less than an ideal native counterpart.

**Comment by gliechtenstein** [comment]
Maybe we are talking about different things. I just tried the link you shared on my phone and recorded it as video. Here's what it looks like: https://youtu.be/jogQP_RBYGU

If yours doesn't feel this way, then there's something wrong.

**Comment by cpg** [comment]
You are scrolling way too fast. If you scroll like you would read through post headlines or something, you will feel it's laggy at certain intervals. I will see if i can post a video (though you said you noticed it too right at the start!). Anyway, it's a minor jumpiness to it, not major.

**Comment by gliechtenstein** [comment]
I think it must have been a miscommunication. If it was actually bad I would have been working on it.

I do tell people that the particular jasonpedia view page with many components can feel choppy exactly for the reasons I mentioned above. But that's the only page I notice any issues. Maybe this is what you heard from me?

Please do share the video, and also share the device spec you're using. I just went back and tried scrolling slow, and it works fine. maybe it feels different on different devices but I have no idea because I only can test on a couple of different devices. If that's the case I will be sure to take a look at this with high priority

**Comment by cpg** [comment]
As I said above, it's not high priority by any stretch. I just added it in case someone at some point wants to look into it.

Scrolling does not feel native-smooth in virtually any of the Jasonette apps I have tested (typically in Jason), where there is more than a pageful of scrolling (i.e. not in simple lists of labels). There is always a jumpy feel to it.

See if you notice in [this video](https://dl.dropboxusercontent.com/u/364883/Screenshots/scroll-in-je.mov). In Jasonedia I notice it as well in View > Component > Image.

My device is an iphone 6 with the latest ios as of this writing (10.1.1) and not much running on it.

Again -- a small thing that, if fixed, would make things smoother and even more indistinguishable from native.

**Comment by gtramontina** [comment]
I was looking at the videos and I couldn't really see the difference. Could it be something related to iOS' momentum or something? What I mean is, if there's any lag or performance impact, it is not _that_ evident.

What do you think about this: repurpose this issue or close it and open another with an example that really shows off and highlights what the problem might be… Call it something like `Screen stutters with lots of heavy components` and label it `help wanted`. We'll also need some benchmark data to support us. This example could be an oversized version of what we have in jasonpedia. 💭?

One thing I think is important to highlight is that Jasonette _is_ native. We need to be careful to not plant a doubt seed into newcomers mind… 😄

**Comment by ghost** [comment]
Just wanted to add my feedback. I gave an app written with Jasonette-ios to a friend which had ~ 15 items, each item has a small 64x64 image, and a title - typical "media" object layout.

The first feedback I got was how choppy/ragged the scrolling was - iPhone 7 plus, so not a hardware issue.

@gtramontina I know Jasonette _is_ native, but unless it looks/behaves like it too that point is moot with the users. This isn't a problem with lots of heavy components, the iPhone 7's processor is more than capable of handling scrolling a dozen or so media objects (using bootstrap terminology)

**Comment by gliechtenstein** [comment]
@darenr can you share the JSON? Like I mentioned, that's not supposed to happen for most apps.

I have iPhone 5, iPhone 6 and an iPad mini. I can try it out.

**Comment by ghost** [comment]
@gliechtenstein absolutely, appreciate you taking a look: https://www.jasonbase.com/things/Lrz.json

what it appears to be, from looking at the screen carefully is that as some element goes out of view some event fires which injects a minor delay which suspends the disbelief of the screen view being a physical object that's being manipulated.

**Comment by ghost** [comment]
**I made progress on understanding this a little**. The choppiness occurs **when a new section scrolls into view**. I can easily see this now when I write the json to position the section change at a different point - basically adding to each section a big space eliminates the choppy scrolling until we get to the section transition. I hope this helps understand it better so you can see what's going on at that point.

**Comment by gliechtenstein** [comment]
## Here's the fix
First things first, please try this branch I just pushed: https://github.com/Jasonette/JASONETTE-iOS/tree/scroll_improvement It's improved a lot.

## The nature of the problem
That said, I want to clarify what this problem is, and what it is not:

This is NOT a matter of feeling "native" vs. "non-native". This is a "native" problem. In fact, this is one of the most common problems iOS developers deal with. Just take a look at all the [google search results for "UITableView jerky"](https://www.google.com/search?q=uitableview+jerky&oq=uitableview+jerky&aqs=chrome..69i57.2599j0j7&sourceid=chrome&ie=UTF-8)

Actually if you really want to see this problem in action, please try opening your iOS mail app (yes, the default mail app that ships with the iPhone). When you have multiple accounts added to the mail app, you will feel the jerkiness as you bring the app from background to foreground and start scrolling after a bit of inactivity. 

I don't know if you guys have tried HTML5-built apps, but the scrolling problem there is on a completely different level than this. It's more about how responsive the scroll is to your touch than if there's a frame skip. Once you try those apps you will get why people talk about building apps natively.

## So why does this problem happen on a native app?
The problem happens because of the way iOS handles scrolls.

Basically, when you have 1000 rows on your screen, there will be only like 10 rows that are visible at a time. The OS doesn't render the rest 990 until you start scrolling. And as you start scrolling, it creates a new row by recycling the row that just disappeared. This way it doesn't have to keep all 1000 cells in memory, it just needs about 12. Still it gives the illusion that there are all 1000 rows in the out-of-screen area.

This recycling scheme works well when you're dealing with static content with static width and static height, because when you recycle one cell with another, they all have the same dimension, therefore no drastic change of each cell size as you scroll.

But it becomes hard as we start dealing with dynamic content that needs to adjust itself in realtime as you scroll. Because, in this case when you take the row that just disappeared and try to reuse it, you need to make sure the cell has the right dimension to fit the new content, etc. 

There are many techniques used to deal with this, but they're all a matter of optimization. For example, instead of having to calculate the width and height in realtime you could send already adjusted images from the server so the client knows exactly what their sizes are, etc. Most app developers use several of these techniques to make their apps perform well.

## Jasonette and optimization
Jasonette is a general purpose app that needs to take care of all these special cases, but in a more generic way. That's what makes it non-trivial. Like I mentioned above, if you're building a single app, you can hardcode all the optimizations, but Jasonette shouldn't try to do that. It instead needs to find the most severe bottlenecks and start optimizing from there.

That's why until now Jasonette really had no optimization logic, and that's where some of the jerkiness came from.

With the new branch I've added some optimization logic. I think there are more ways we can optimize this further going forward, but I think it's a good start, and for now I think it's good enough.

Please try it out and let me know so I can decide where to go from here: https://github.com/Jasonette/JASONETTE-iOS/tree/scroll_improvement

**Comment by cpg** [comment]
My feeling is that it's substantially improved. Great job!

In longer lists (like in the RackerLogger app, under the longer list of rackets with 60 to 80 items) one can still notice the issue a little bit, but it's barely noticeable. I worked in CPU/GPU optimizations way back when DVD play was the rage on laptops and I guess I'm still more sensitive that the average user for these things.

I did not realize it needed so much optimization work. I created this as something to track in the future and not critical, as I mentioned. I thought maybe it was some small setting somewhere.

As you said, I think it's good enough. Any more optimization in the future will be welcome, but this is great. Awesome job!

**Comment by ghost** [comment]
Appreciate the optimizations.

I just built it and gave it a try, but sadly I don't see any/much improvement, maybe a little, but this is really binary, it's either smooth and fluid or choppy - and it's maybe less choppy but marginally. For a reference open Apple's News app, I have pages and pages of stories and it scrolls perfectly smoothly - obviously they have the advantage of fixed height. Actually, my app has fixed height cells too, which brings me to my next point, given that this is obviously hard to optimize, is there something I can do in the app json to help? In html one simple way is height+overflow hidden, this guarantees fixed sizes, Can I help optimize jsonette with any style tags?  

I've worked with layout managers that use a scrollport like iOS the usual/best practice issue for knowing cell height is to keep a dictionary. it's usually possible to know the cell height before you've started rendering. Although the data is loaded dynamically I'm not sure that cell height really is dynamic in Jasonette, aside from images which is usually solved using a placeholder. It's not possible inside of a cell's rendering to change the height dynamically as far as I know, I can't for example set height using a function - variable substitution is all known _before_ rendering starts. So I think that if you create a dictionary of cell heights then use the async image loaded handler to update as/when images have a dimension it will make scrolling smooth. I suspect it was being calculated every frame by summing which is of course inefficient. That said, for a dozen items I'm really surprised that the quad core processor can't keep up with 60fps with even the most inefficient code. I would totally understand if it was 1000 elements with lots and lots of images, but I need(ed) only a dozen. 

Anyway, thanks for the fix.

**Comment by cpg** [comment]
My two apps went live with these new performance improvements. It may not be perfect (maybe because my apps do not have fixed height in every row?), but it's noticeably smoother.
