### ISSUE TITLE
body settings in $network.request calls does not work on POSTs

### ISSUE THREAD

**Issue by cpg** [Jasonette/JASONETTE-iOS#66]
the `header` parameter in `$network.request` works and the headers get sent on every request, including POSTs.

however, the `body` setting sends parameters in the URL of GET requests, however, not in the body of some requests, specifically POSTs.

I debugged this through on of my apps. I strongly recommend using the `header` setting.

**Comment by gliechtenstein** [comment]
As discussed in the [contributing guideline](https://github.com/Jasonette/JASONETTE-iOS/blob/develop/CONTRIBUTING.md#do-you-have-a-bug-report-or-a-feature-request), please always:

1. post the code that can replicate the problem
2. AS WELL AS step by step description of how.

More specifically, what does it mean by "not in the body of some requests"? When does it happen and when does it not happen? What exactly did you do?

Without all this information, no one will be able to take a look at the problem.

I am closing this for now, because if this actually is a problem, I want an actual detailed clear description and title at the top instead of conversations dragging along. Please start a new issue with more clear description of the situation. Thank you.

**Comment by cpg** [comment]
I mostly wrote this up to save others from the hassle of having to debug this in their apps. When I have some time, I will document it. Closing it is ok for now (I am actually thinking it could be related to AFNetworking or some other library/stack issue).
