### ISSUE TITLE
BLOCKER: master branch doesn't compile in xcode

### ISSUE THREAD

**Issue by pzsfeng** [Jasonette/JASONETTE-iOS#70]
Hi,

This looks like a great framework. I am a golang, C/C++ developer, new to xcode and jasonette. I downloaded the latest package from the site and from the master branch. I followed the instructions on the video and gave it a try.

Both the packages fail to compile in xcode with error:

REmenulfile.h not found
SBJason4Writer.h not found.

Am I missing something? Please let me know. 

I am looking forward to try this out.

Thanks,
Pinkesh

**Comment by gliechtenstein** [comment]
Can you confirm it's the master branch you downloaded?

By the way, the default branch on the github landing page is `develop`. You get `master` only if you download from here: https://jasonette.github.io/documentation/ (The stable version)

**Comment by pzsfeng** [comment]
I downloaded the zip folder from website and then also git cloned the repo. You're right I might have used the develop branch from the repo.

Any recommended branch that I should try out?

Thanks for the quick response!

**Comment by gliechtenstein** [comment]
Sorry for the inconvenience. Could you:

1. Re-download the [develop branch](https://github.com/Jasonette/JASONETTE-iOS/archive/develop.zip) right now, and share the result
2. After that, try downloaing from [master](https://github.com/Jasonette/JASONETTE-iOS/archive/master.zip) and see if that works?

I know that `master` works without problem, so if you have trouble even getting master to work, it's a critical problem and I have to fix it immediately.

I **do** recommend using `develop` though, since it's mostly stable and has a lot of bugs fixed and added a lot of features since the last merge with `master`. So ultimately I recommend develop.

But for now I would appreciate it if you could share the result for both. Thank you!

**Comment by gliechtenstein** [comment]
Also, just to make sure, the right way to open it is either:

1. [Recommended] Run the `Setup` command located at the root folder
2. [Advanced] Open `Jasonette.xcworkspace` file in the `app` folder

**What you should NOT do is** launch by opening `Jasonette.xcodeproj`. That may result in the project not being able to find all the linked libraries.

**Comment by pzsfeng** [comment]
> What you should NOT do is launch by opening Jasonette.xcodeproj. 

This is my mistake. I didn't run setup binary (was following the video). It works now. Thanks for quick followup.

Excited to try this out.
