### ISSUE TITLE
How to update a property of an item?

### ISSUE THREAD

**Issue by ringfox** [Jasonette/JASONETTE-iOS#78]
When I use $each, how to update one of it's property,and update($render) the view to show the new state. 

e.g. When an user touched the like button on one of the image the twitter timeline. how to highlight the like button of the specified row.

or is there any way to get the index of an item, in the $each iteration.

Do I make sense?  

Appreciated!Thank you!

**Comment by gliechtenstein** [comment]
Before we dive in, I would like to mention that Jasonette was built primarily as a REST client (networking client), which is why it lacks a lot of local-only features like this out of the box.

Normally what I would recommend is, instead of doing all this locally, set up a server with persistent database, and all you need to do is make a POST request and update the DB entry, after which you just refresh the view and it will display the correct state straight from the server. That way you don't have to worry about all these frontend-only engineering.

That said, let me show you how to do this. You can basically achieve this using [local variables](https://jasonette.github.io/documentation/actions/#variable) and some javascript to manipulate them.

Here's the gist:

1. You add an additional attribute to each entry called "selected" (or "highlighted").
2. Then while you're iterating through the template using `#each` you conditionally style them using [#if](https://jasonette.github.io/documentation/templates/#2-conditional-ifelseifelse). That way, depending on the state of the 'selected' attribute, you can make it show up as selected or not.
3. To toggle these states on and off, you need to create an action (let's call it `like`) under `$jason.head.actions` and trigger it whenever user taps on it, and pass the item's ID as an `option`, so it can be processed.
4. Then inside the `like` action, you first set the `currently_selected` index, and then use that index to update the original array.

Here's an example: https://jasonbase.com/things/VVM/edit

```json
{
  "$jason": {
    "head": {
      "actions": {
        "$load": {
          "type": "$set",
          "options": {
            "orders": [
              {
                "id": "0",
                "name": "americano",
                "selected": "false"
              },
              {
                "id": "1",
                "name": "blueberry scone",
                "selected": "false"
              },
              {
                "id": "2",
                "name": "tazo chai",
                "selected": "false"
              }
            ]
          },
          "success": {
            "type": "$render"
          }
        },
        "like": {
          "type": "$set",
          "options": {
            "currently_selected": "{{id}}"
          },
          "success": {
            "type": "$set",
            "options": {
              "orders": "{{var new_orders=$get.orders; new_orders[parseInt($get.currently_selected)]['selected']='true'; return new_orders;}}"
            },
            "success": {
              "type": "$render"
            }
          }
        }
      },
      "templates": {
        "body": {
          "sections": [
            {
              "items": {
                "{{#each $get.orders}}": {
                  "type": "horizontal",
                  "components": [
                    {
                      "type": "label",
                      "text": "{{name}}"
                    },
                    {
                      "type": "button",
                      "text": "like",
                      "action": {
                        "trigger": "like",
                        "options": {
                          "id": "{{id}}"
                        }
                      },
                      "style": [
                        {
                          "{{#if selected=='true'}}": {
                            "background": "#cecece",
                            "color": "#ffffff"
                          }
                        },
                        {
                          "{{#else}}": {
                            "background": "#0000ff",
                            "color": "#ffffff"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

And here's what it looks like:

![img_1183](https://cloud.githubusercontent.com/assets/16613330/21064404/80869f76-be28-11e6-94f3-f175b0754da2.PNG)



Hope this makes sense!

**Comment by gliechtenstein** [comment]
By the way feel free to ask usage related questions on https://forum.jasonette.com That's much more visible and probably more helpful for others in the future :)

**Comment by ringfox** [comment]
Cool, you are so kind. Thank you for your excellent work.
