### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/JASONETTE-iOS#82]
Implement a loading indicator for asynchronous tasks, just like how the Android version does.

![screenshot_20161216-125814](https://cloud.githubusercontent.com/assets/16613330/21273006/908d53a8-c38f-11e6-95ed-c6539f092f5b.png)

**Comment by cpg** [comment]
Please don't make it "like in Android."

The one in the Android app displays a WHOLE WHITE PAGE with an indicator on it in between loads. It's jarring for apps that are not mostly white, and it makes apps feel like browsers from 20+ years ago where the whole page was blanked and redisplayed.

A transparent indicator (with maybe some translucency to minimally occlude the current page), would be better.

In my apps I already implemented a default background to match the rest of the app so that the jarring whole-blank-page for two to 5 seconds (in the case of access via data network) does not make it look so bad.

**Comment by gliechtenstein** [comment]
@cpg yes will probably use some widely used nice looking library. On Android I honestly couldn't find any non-obtrusive loading indicator library. The official Android one that I ended up choosing was the best looking of them all actually. 

However on iOS.... it's pretty hard to find bad looking UI libraries haha

**Comment by gliechtenstein** [comment]
Closed with https://github.com/Jasonette/JASONETTE-iOS/pull/87
